---
abstract: 'tiny perl module for sending Growl notifications on Mac OS X'
author:
  - 'Alex White <VVu@geekfarm.org>'
build_requires:
  English: 0
  Test::More: 0.88
  utf8: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.102341, CPAN::Meta::Converter version 2.102400'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Growl-Tiny
requires:
  Carp: 0
  Exporter: 0
resources:
  repository: http://github.com/wu/Growl-Tiny
version: 0.0.3
